apiVersion : apps/v1
kind: Deployment
metadata:
  name: TradeProjectService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TradeProjectService
  template:
    metadata:
      labels:
        app: TradeProjectService
    spec:
      containers:
        - name: TradeProjectService
          image: mainstxcr.azurecr.io/TradeProjectService
          ports:
          - containerPort: 80